const data = [
  {
    id: "best-01",
    image: process.env.PUBLIC_URL + "/img/item01.jpg",
    desc: "고오오오급 버전 신라면이 나왔다",
    title: "농심 신라면 GOLD",
    price: "10,900원",
    // price_two: 8900,
  },
  {
    id: "best-02",
    image: process.env.PUBLIC_URL + "/img/item02.jpg",
    desc: "열나게 화끈한 매운 라면!",
    title: "오뚜기 열라면",
    price: "5,900원",
  },
  {
    id: "best-03",
    image: process.env.PUBLIC_URL + "/img/item03.jpg",
    desc: "사골곰탕에 특수 후추를 뿌려넣은 라면",
    title: "오뚜기 순후추 라면",
    price: "8,900원",
  },
  {
    id: "best-04",
    image: process.env.PUBLIC_URL + "/img/item04.jpg",
    desc: "칼칼하고 두꺼운 건면 라면",
    title: "농심 얼큰 장칼국수",
    price: "7,200원",
  },
  {
    id: "best-05",
    image: process.env.PUBLIC_URL + "/img/item05.jpg",
    desc: "완도산 다시마 2개!",
    title: "오뚜기 오동통면",
    price: "4,980원",
  },
  {
    id: "best-06",
    image: process.env.PUBLIC_URL + "/img/item06.jpg",
    desc: "오리지날 진라면에 약간의 매운맛으로 한층 더 진화",
    title: "오뚜기 진라면(약간매운맛)",
    price: "6,500원",
  },
  {
    id: "best-07",
    image: process.env.PUBLIC_URL + "/img/item07.jpg",
    desc: "우지로 맛을 낸 고소한 면과 깊고 진한 풍미의 프리미엄 라면",
    title: "삼양 1963 삼양라면",
    price: "8,900원",
  },
  {
    id: "best-08",
    image: process.env.PUBLIC_URL + "/img/item08.jpg",
    desc: "횡성군 출신 한우를 사용한 라면",
    title: "삼양 쇠고기면",
    price: "5,600원",
  },
  {
    id: "best-09",
    image: process.env.PUBLIC_URL + "/img/item09.jpg",
    desc: "짱구는 못말려 콜라보 라면, 배불러라면",
    title: "팔도 짱구는 배불러라면",
    price: "1,600원",
  },
  {
    id: "best-10",
    image: process.env.PUBLIC_URL + "/img/item10.jpg",
    desc: "착한 소비자가격, 맛도 착한 라면!",
    title: "노브랜드 라면 한그릇 순한맛 10개",
    price: "9,200원",
  },
  {
    id: "best-11",
    image: process.env.PUBLIC_URL + "/img/item11.png",
    desc: "횡성군 출신 한우를 사용한 라면",
    title: "삼양 쇠고기면",
    price: "5,600원",
  },
  {
    id: "best-12",
    image: process.env.PUBLIC_URL + "/img/item12.png",
    desc: "야식으로 딱! 살찔 걱정없는 짜장라면",
    title: "킬로리 제로콘누들 다이어트 짜장라면 6개",
    price: "23,550원",
  },
  {
    id: "best-13",
    image: process.env.PUBLIC_URL + "/img/item13.png",
    desc: "야식으로 딱! 살찔 걱정없는 비빔면",
    title: "저당 제로콘누들 선면 비빔면 6box",
    price: "22,310원",
  },
  {
    id: "best-14",
    image: process.env.PUBLIC_URL + "/img/item14.jpg",
    desc: "담백하고 칼칼한 닭국수라면",
    title: "팔도 꼬꼬면 5개",
    price: "4,970원",
  },
  {
    id: "best-15",
    image: process.env.PUBLIC_URL + "/img/item15.jfif",
    desc: "진한 돼지 김치찌개 바로 그 맛!",
    title: "하림 양푼김치찌개라면 4개",
    price: "4,070원",
  },
  {
    id: "best-16",
    image: process.env.PUBLIC_URL + "/img/item16.jpg",
    desc: "건면과 홍게의 진한 바닷맛이 가득한 짬뽕라면",
    title: "풀무원  로스팅 짬뽕 홍게 4개",
    price: "3,980원",
  },
];

export default data;
